packages:
  - packages/*
  - tests
  - devlink

allowBuilds:
  '@parcel/watcher': false
  msgpackr-extract: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@roblox-ts/rojo-resolver@1.2.0'
