name: Test create-roblox-ts

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [game, place, model, plugin, package]
    steps:
      - name: Checkout roblox-ts repo
        uses: actions/checkout@v4
        with:
          path: roblox-ts

      - name: Setup roblox-ts repo
        uses: ./roblox-ts/.github/actions/setup
        with:
          directory: roblox-ts

      - name: Pack workspace packages
        working-directory: roblox-ts
        run: |
          pnpm --filter @rbxts/compiler-types pack --out "$PWD/compiler-types.tgz"
          pnpm --filter @roblox-ts/luau-ast pack --out "$PWD/luau-ast.tgz"
          pnpm --filter @roblox-ts/path-translator pack --out "$PWD/path-translator.tgz"
          pnpm --filter @roblox-ts/rojo-resolver pack --out "$PWD/rojo-resolver.tgz"
          pnpm --filter roblox-ts pack --out "$PWD/roblox-ts.tgz"
          pnpm --filter @roblox-ts/cli pack --out "$PWD/cli.tgz"

      - name: Create template project
        run: npm init roblox-ts@latest ${{ matrix.type }} -- -y --dir project --skipBuild

      - name: Install local roblox-ts
        run: |
          cd project
          npm install ../roblox-ts/compiler-types.tgz ../roblox-ts/luau-ast.tgz ../roblox-ts/path-translator.tgz ../roblox-ts/rojo-resolver.tgz ../roblox-ts/roblox-ts.tgz ../roblox-ts/cli.tgz

      - name: Build
        run: |
          cd project
          npm run build
