name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: roblox-ts/setup-rokit@v0.1.2

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Validate ts-expose-internals
        run: |
          pnpm --dir packages/ts-expose-internals run compile
          pnpm --dir packages/ts-expose-internals test

      - name: Run Tests
        run: pnpm test

      - name: Upload Test Output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-output-${{ matrix.os }}
          path: tests/out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
